-- create default roles
INSERT INTO ROLE (ID, CREATED, UPDATED, ROLE) VALUES (1, CURRENT_TIMESTAMP, null, 'ROLE_ADMIN');
INSERT INTO ROLE (ID, CREATED, UPDATED, ROLE) VALUES (2, CURRENT_TIMESTAMP, null, 'ROLE_USER');

-- create default admin user
INSERT INTO USER (ID, CREATED, UPDATED, FIRSTNAME, LASTNAME, USERNAME, PASSWORD, ENABLED, VALIDATED, COMMENT) VALUES (1, CURRENT_TIMESTAMP, null, 'Ramy', 'Abi-Samra', 'ramy@therapie.com', '$2a$10$zJC/Zsp8rqobjbBOiY0rsecPYMH2v09N8ZpFzptJ32/xsiW.yazje', TRUE, TRUE, 'password is password');

-- assign default admin user to all roles
INSERT INTO USER_ROLES (USER_ID, ROLE_ID) VALUES (1, 1);
INSERT INTO USER_ROLES (USER_ID, ROLE_ID) VALUES (1, 2);

-- create some default clients
INSERT INTO CLIENT (ID, CREATED, UPDATED, EMAIL, FIRSTNAME, LASTNAME, PHONENUMBER) VALUES (1, CURRENT_TIMESTAMP, null, 'email1@example.com', 'firstname', 'lastname', '1234567890');
INSERT INTO CLIENT (ID, CREATED, UPDATED, EMAIL, FIRSTNAME, LASTNAME, PHONENUMBER) VALUES (2, CURRENT_TIMESTAMP, null, 'email2@example.com', 'firstname', 'lastname', '1234567890');
INSERT INTO CLIENT (ID, CREATED, UPDATED, EMAIL, FIRSTNAME, LASTNAME, PHONENUMBER) VALUES (3, CURRENT_TIMESTAMP, null, 'email3@example.com', 'firstname', 'lastname', '1234567890');
INSERT INTO CLIENT (ID, CREATED, UPDATED, EMAIL, FIRSTNAME, LASTNAME, PHONENUMBER) VALUES (4, CURRENT_TIMESTAMP, null, 'email4@example.com', 'firstname', 'lastname', '1234567890');
