INSERT INTO CLIENT (ID, CREATED, UPDATED, EMAIL, FIRSTNAME, LASTNAME, PHONENUMBER) VALUES (1, CURRENT_TIMESTAMP, null, 'email1@example.com', 'firstname', 'lastname', '1234567890');
INSERT INTO CLIENT (ID, CREATED, UPDATED, EMAIL, FIRSTNAME, LASTNAME, PHONENUMBER) VALUES (2, CURRENT_TIMESTAMP, null, 'email2@example.com', 'firstname', 'lastname', '1234567890');
INSERT INTO CLIENT (ID, CREATED, UPDATED, EMAIL, FIRSTNAME, LASTNAME, PHONENUMBER) VALUES (3, CURRENT_TIMESTAMP, null, 'email3@example.com', 'firstname', 'lastname', '1234567890');
INSERT INTO CLIENT (ID, CREATED, UPDATED, EMAIL, FIRSTNAME, LASTNAME, PHONENUMBER) VALUES (4, CURRENT_TIMESTAMP, null, 'email4@example.com', 'firstname', 'lastname', '1234567890');
